### ISSUE TITLE
Multisite usage

### ISSUE THREAD

**Issue by farkasf89** [wirecard/woocommerce-ee#260]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version:** 3.6.5  
**PHP version:** 7.2

### Issue

**Problem description:**

We created a Wordpress multisite network with the same version of Woocommerce and Woocommerce Global Cart plugin, but when we try activate the plugin, we got this message:
"Sorry, but this plugin requires the Wirecard WooCommerce Extension to be installed and active."

How can we use your plugin with multisite network?
Thank you for your help!

**Comment by rinnhofer** [comment]
Hello @farkasf89 ,

thank you for noticing us about this issue. We will look into the multisite support as soon as possible and give you an update with all needed information on how to use multisite network with our extension.

Kind regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hello @farkasf89 ,

could you please provide the folder location of your WooCommerce installation? Currently we check if WooCommerce is installed via methods provided by WordPress, these include "active_sitewide_plugins" which is described to include network plugin files as well. This would help to find the root cause of the issue.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hello,

since you did not respond I assume your issue is resolved.
If you have further questions feel free to reopen the issue.

Best regards,
Wirecard Shop Systems Team

**Comment by nikonratm** [comment]
This issue is definitely not fixed. Your code is incorrect. First of all this is not the usual method of checking for an active plugin but the real issue is that your code looks for plugin names immediately in the array but the array is keyed like
```
Array
(
    [woocommerce/woocommerce.php] => 1528243035
)
```

So line 379 should be `foreach ( $sitewide_plugins as $plugin_name => timestamp) {`
