### ISSUE TITLE
Translation strings being replaced by incomplete translation

### ISSUE THREAD

**Issue by petercpg** [wirecard/woocommerce-ee#357]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version:** 3.8 and 4.0.1
**PHP version:** 7.3  

### Issue

**Problem description:**

The language files bundled with Wirecard WooCommerce extension releases is being replaced by some incomplete translation via WordPress translation auto-update feature, which breaks the UI interface in WP/WooCommerce Dashboard.

My environment provides i18n in en-US & zh-TW locales, while only zh-TW is affected by this issue. 

**Screenshot**
![Screenshot](https://user-images.githubusercontent.com/205738/79109367-ca4a4a00-7daa-11ea-8f00-7ae4ebb1c7fd.png)

**Steps to reproduce:**
* Install a slightly older version of WordPress, WooCommerce, and Wirecard WooCommerce extension
* Switch the WordPress UI to zh-TW locale
* The translation of Payment methods should be alright in Dashboard -> WooCommerce -> Settings -> Payments and Dashboard -> WooCommerce -> Wirecard Payment Gateway page
* Have the translation updated either automatically or manually by upgrading WordPress or extension itself
* The translation is now broken
* Deleting `wirecard-woocommerce-extension-zh_TW.po` and `wirecard-woocommerce-extension-zh_TW.mo` located in `ABSPATH/wp-content/languages/plugins/` recovers the localization message but it is gone again once the language files are updated

**Comment by petercpg** [comment]
stale gettext message files: [wirecard-woocommerce-extension-zh_TW.zip](https://github.com/wirecard/woocommerce-ee/files/4468998/wirecard-woocommerce-extension-zh_TW.zip)

**Comment by tomazpu** [comment]
Hello @petercpg, 

we will look into your issue and try to reporduce it. Thank you for the detailed description.

Best regards, 
Tomaz

**Comment by edra-bumci** [comment]
Hello @petercpg,

we looked into this issue and it should be working now again for you. Thank you for your input.

Best regards,
Edra

**Comment by petercpg** [comment]
Hi @edra-bumci, I still have this issue reproducible by removing the Wirecard plugin, clearing out the plugin folder and database tables, then re-install.

My versions running now:
- PHP 7.3.19
- Wordpress 5.4.2
- WooCommerce 4.2.0
- Wirecard WooCommerce Extension 3.3.0

My two cents: I think the issue here is the plugin still pulls old translation from somewhere (maybe https://translate.wordpress.org/locale/zh-tw/default/wp-plugins/wirecard-woocommerce-extension/ ? ) to wp-content/languages/plugins, which has the preference than the good tranlation files shipped with the plugin itself. 

We can probably either block the l10n auto-update feature, or sync the latest zh-TW PO files to the translation platform?

**Comment by edra-bumci** [comment]
Hi @petercpg,

There is a folder where translations are pulled in wordpress inside wp-content/translations. Please remove all the hashed translation files inside this folder concerning the tw language 'zh_TW-hashcode'. Then navigate again in wordpress backend in general settings and translate again to zh_TW.
This should fix your problem.

Best regards,
Edra
Wirecard Shop Extensions Team

**Comment by petercpg** [comment]
Hi @edra-bumci, it works right after those files are removed. 

However, once Wordpress tries to detect for updated version of wordpress/plugins/themes again, it shows there is an updated version of translation. The plugin translation is broken again when it actually updates.

Now I can notice the updated PO file is tracking with development (trunk) branch (while it was previously on master) but the contents are still obsolete.

Here are the updated file pulled, after the zh-TW-hashed json files being cleared out: [wirecard-woocommerce-extension-zh_TW-stale-2.zip](https://github.com/wirecard/woocommerce-ee/files/4818880/wirecard-woocommerce-extension-zh_TW-stale-2.zip)
